name: spaces;
generated-by: gregorio 4.1.0-beta3-fix-905-2e2e49a-3303;
%%
(c3){fg!hi}(fg!hi) {fg/0hi}(fg/0hi) {fg/hi}(fg/hi) {fg//hi}(fg//hi) {fg hi}(fg hi) {fg!/0hi}(fg/0hi) {fg!/hi}(fg!/hi) {fg!//hi}(fg!//hi) {fg! hi}(fg! hiZ)
{fg/<v>[1.3]</v>hi}(fg/[1.3]hi) {fg!/<v>[-0.8]</v>hi}(fg!/[-0.8]hi) {fg//<v>[-0.2]</v>hi}(fg//[-0.2]hi) {fg!//<v>[-.3]</v>hi}(fg!//[-.3]hiZ)
æ(dc) æ(ab/dc) {c/!d f!/!g}(c/!d f/!g) 
