name: auto-fusion;
generated-by: gregorio 4.0.0-fix-679-fc2dd93-2784;
%%
(c3)h!@<v>[</v>iw_jijih<sp>~</sp><v>]</v>(h!iw_@ji@j@ih~) @<v>[</v>jhigjk<v>]</v>(jh@ig@jk) @<v>[</v>j@higjk<v>]</v>(j@h@ig@jk) @<v>[</v>jhi<gjk<v>]</v>(jhi<@g@jk) @<v>[</v>f<v>]</v>(f) @<v>[</v>-ehigjk><v>]</v>(-e@h@ig@jk>) @<v>[</v>gh_g_!@if<v>]</v>(g@h_g_!@if) @<v>[</v>gh_g_!if<v>]</v>(g@h_g_!@if) @<v>[</v>HGhg<v>]</v>(HG@hg) @<v>[</v>IGhf<v>]</v>(IG@hf) @<v>[</v>FGhg<v>]</v>(FG@hg) @<v>[</v>EGig<v>]</v>(EG@ig) @<v>[</v>goed<v>]</v>(go@ed) @<v>[</v>geod<v>]</v>(g@eod) @<v>[</v>geoc<v>]</v>(g@eoc) @<v>[</v>hVfe<v>]</v>(hV@f_e) @<v>[</v>hvfe<v>]</v>(hv@fe) @<v>[</v>fVij<v>]</v>(fV@ij) @<v>[</v>fvij<v>]</v>(fv@ij) (::) 
