name: clivis;
generated-by: gregorio 4.0.0-rc2-fix-670-af3219a-2704;
%%
(c3)gf<(gf<) gf>(gf>) -gf(-gf) gf<sp>~</sp>(gf~z) g.f(g.f) gf.(gf.) gf..(gf..) g.f.(g.f.z) g'f(g'f) gf'(gf') g'f'(g'f') h'f(h'f) hf'(hf') h'f'(h'f'z) g_f(g_f) gf_(gf_) g_f_(g_f_) h_f(h_f) hf_(hf_) h_f_(h_f_z) g.'f(g'.f) gf'.(gf'.) g'.f'.(g'.f'.) h.'f(h'.f) hf.'(hf'.) h.'f.'(h'.f'.z) g.'fo(g'.f) gfo'.(gf'.) go'.fo'.(g'.f'.) h.'fo(h'.f) hfo.'(hf'.) h.'fo.'(h'.f'.z) gof<(gof<) gof>(gof>) -gof(-gof) gof<sp>~</sp>(gof~z) g.of(go.f) gof.(gof.) gof..(gof..) g.of.(go.f.z) go'f(go'f) gof'(gof') g'of'(go'f') h'of(ho'f) hof'(hof') h'of'(ho'f'z) g_of(go_f) gof_(gof_) g_of_(go_f_) h_of(ho_f) hof_(hof_) h_of_(ho_f_z) g.o'f(go'.f) gof'.(gof'.) g'o.f'.(go'.f'.) ho.'f(ho'.f) hof.'(hof'.) ho.'f.'(ho'.f'.z) 
