name: fusion-oriscus;
generated-by: gregorio 4.0.0-fix-679--;
%%
(c3)f@gOh(f@gOh) f@gOi(f@gOi) e@gOh(e@gOh) e@gOi(e@gOi) f@go@hi(f@go@hi) e@go@ij(e@go@ij) f@gO@hi(f@gO@hi) e@gO@ij(e@gO@ij) e@gO!@fdf(e@gO!@fdf) d@eo@fd(d@eo@fd) d@eo@gd(d@eo@gd) d@eo<@fd(d@eo<@fd) d@eo<@gd(d@eo<@gd) d!eo<@fd(d!eo<@fd) d!eo<@gd(d!eo<@gd) do@f@gfh<(do@f@gfh<) co@e@gfh<(co@e@gfh<) c@eo@fd(c@eo@fd) g@eo@fd(g@eo@fd) e@go(e@go) d@eo_@fd(d@eo_@fd) d@eo_@f_d(d@eo_@f_d) d@eo_@gd(d@eo_@gd) d@eo'_@g_d(d@eo'_@g_d) d.@eo_@fd(d.@eo_@fd) gO@ij(gO@ij) gO@ed(gO@ed) g@eo(g@eo) g@eo@g(g@eo@g) g@eo@f(g@eo@f) g@eo@d(g@eo@d) g@eo@c(g@eo@c) c@eo@f(c@eo@f) c@eo@g(c@eo@g) c@eo(c@eo) c@eo@c(c@eo@c) do@eo@go(do@eo@go) (::) 
