name: salicus;
generated-by: gregorio 4.0.0-rc2-fix-670-fefd9da-2697;
initial-style: 0;
%%
(c3)fgoh(fgoh) f!goh(f!goh) fgOh(fgOh) egoh(egoh) egOh(egOh) egoi(egoi) egOi(egOiz) fgoh<(fgoh<) egoh<(egoh<) egoi<(egoi<) fgoh>(fgoh>) egoh>(egoh>) egoi>(egoi>) fgoh<sp>~</sp>(fgoh~) egoh<sp>~</sp>(egoh~) egoi<sp>~</sp>(egoi~z) fgOh<(fgOh<) egOh<(egOh<) egOi<(egOi<) fgOh>(fgOh>) egOh>(egOh>) egOi>(egOi>) fgOh<sp>~</sp>(fgOh~) egOh<sp>~</sp>(egOh~) egOi<sp>~</sp>(egOi~z) fgOh'_(fgOh'_) egOh'_(egOh'_) egOi'_(egOi'_) fgOh<'_(fgOh'_<) egOh<'_(egOh'_<) egOi<'_(egOi'_<) f'_gOh>(f'_gOh>) egO'_h>(egO'_h>) egO'_i>(egO'_i>) fgOh<sp>~</sp>'_(fgOh'_~) egOh<sp>~</sp>'_(egOh'_~) egOi<sp>~</sp>'_(egOi'_~z) 
