name: shapes;
generated-by: gregorio 4.1.0-beta1-fix-697-1abc209-3047;
%%
(c3)fg(fg) gvFE(gvFE) ghg(ghg) ghgh(ghgh) ghghg(ghghg) gqh(gqhq) gFE<(gFE<) gFE<sp>~</sp>(gFE~) gs(gs) gs<(gs<) gf(gf) g=(g=) h=(h=) fvE'D.(fvE'D.) gvFD(gvFD) hvGD(hvGD) ivHD(ivHD) iv>(iv>) ige(ige) ige<sp>~</sp>(ige~) dfec<sp>~</sp>(dfec~) dwfec<sp>~</sp>(dwfec~) egi(egi) egi<sp>~</sp>(egi~) GrGrFr(GrGrFr) GrGrFr<(GrGrFr<<) FrGrFr_0(FrGrFr_0) GrFrEr(GrFrEr) Gr<(Gr<<Z) -fg(-fg) -f'g(-f'g) -f'1g(-f'1g) gf<sp>~</sp>(gf~) g'f<sp>~</sp>(g'f~) g'0f<sp>~</sp>(g'0f~) (:) gor(gor) gor>(gor>) gor<sp>~</sp>(gor~) {g}r/Gr/gor<(gr/Gr/gor<Z) -fg>(-fg>) -fg<(-fg<) fwg>(fwg>) 
