name: torculus;
generated-by: gregorio 4.0.0-rc2-fix-670-af3219a-2704;
%%
(c3)ghg(ghg) fif(fifz) gh.g(gh.g) fi.f(fi.f) ghg.(ghg.) fif.(fif.) g.h.g.(g.h.g.) f.i.f.(f.i.f.) ghg..(ghg..) fif..(fif..z) g_hg(g_hg) f_if(f_if) gh_g(gh_g) fi_f(fi_f) ghg_(ghg_) fif_(fif_) g_h_g_(g_h_g_) f_i_f_(f_i_f_z) g'hg(g'hg) f'if(f'if) gh'g(gh'g) fi'f(fi'f) ghg'(ghg') fif'(fif') g'h'g'(g'h'g') f'i'f'(f'i'f'z) g'hg(g'hg) f'if(f'if) gh.'g(gh'.g) fi.'f(fi'.f) gh.'g(gh'.g) fif.'(fif'.) g'h.'g.'(g'h'.g'.) f'i.'f.'(f'i'.f'.z) -gig<sp>~</sp>(-gig~) ghg.(ghg.) ghg.0(ghg.0) ghg.1(ghg.1) ghg..(ghg..) fgf.(fgf.) fgf.0(fgf.0) fgf.1(fgf.1) fgf..(fgf..)(z) 
