EXPECTED='% File generated by gregorio [0-9]\.[0-9]\.[0-9](-(beta|rc)[0-9]{1,})?(-[a-zA-Z0-9./-_]{1,}-[0-9a-f]{8}-[0-9]{1,})?
\\GregorioTeXAPIVersion\{[0-9]\.[0-9]\.[0-9](-(beta|rc)[0-9]{1,})?\}%
% Name: bad test
\\GreBeginHeaders %
\\GreHeader\{name\}\{bad test\}%
\\GreEndHeaders %
\\GreBeginScore\{[0-9a-f]{40}\}\{9\}\{9\}\{0\}\{0\}\{\}\{4\}\{\\GreInitialClefPosition\{4\}\{0\}\}%
\\GreSetLargestClef\{c\}\{4\}\{3\}\{c\}\{0\}\{3\}%
\\GreScoreOpening\{%
\}\{%
\\GreSetInitialClef\{c\}\{4\}\{3\}\{c\}\{0\}\{3\}\{1\}%
\}\{%
\}\{\\GreSyllable\}\{\\GreSetFirstSyllableText\{\\GreElision\{E\}\}\{\\GreElision\{l\}\}\{\\GreElision\{ision\}\}\{\{\}\{\\GreFirstWord\{\\GreFirstSyllable\{\\GreElision\{\\GreFirstSyllableInitial\{l\}ision\}\}\}\}\{\}\}\{\{\}\{\\GreFirstWord\{\\GreFirstSyllable\{\\GreElision\{\\GreFirstSyllableInitial\{E\}lision\}\}\}\}\{\}\}\{\}\}\{\}\{\\GreFirstWord\}\{1\}\{\\GreSetNextSyllable\{\}\{\}\{\}\{\}\{\}\\GreLastOfLine\}\{\}\{\{18\}\{0\}\}\{\}\{%
\\GreSyllableNoteCount\{1\}%
\\GreLastOfScore\\GreGlyph\{\\GreCPPunctum\}\{9\}\{\\GreNextCustos\{9\}\{\}\}\{0\}%
\{%
\\GreGlyphHeights\{9\}\{9\}%
\}\{\}\{\}%
\}%
%
\\GreEndScore %
\\endinput %'
echo "$EXPECTED"

echo ==========
OUTCOME=$("$gregorio_path" -d -S bad.gabc | tr -d '\r')
echo ==========
echo "$OUTCOME"

[[ "$OUTCOME" =~ $EXPECTED ]] || exit 1
