EXPECTED="% File generated by gregorio [0-9]\.[0-9]\.[0-9](-[a-zA-Z0-9.-]{1,}-[0-9a-f]{8}-[0-9]{1,})?
\\\\GregorioTeXAPIVersion\{[0-9]\.[0-9]\.[0-9]\}%
% Name: bad test
\\\\GreBeginHeaders %
\\\\GreHeader\{name\}\{bad test\}%
\\\\GreEndHeaders %
\\\\GreBeginScore\{[0-9a-f]{40}\}\{9\}\{9\}\{0\}\{0\}\{\}\{4\}\{\\\\GreInitialClefPosition\{4\}\{0\}\}%
\\\\GreSetLargestClef\{c\}\{4\}\{3\}\{c\}\{0\}\{3\}%
\\\\GreScoreOpening\{%
\}\{%
\\\\GreSetInitialClef\{c\}\{4\}\{3\}\{c\}\{0\}\{3\}\{1\}%
\}\{%
\}\{\\\\GreSyllable\}\{\\\\GreSetFirstSyllableText\{\\\\GreElision\{E\}\}\{\\\\GreElision\{l\}\}\{\\\\GreElision\{ision\}\}\{\{\}\{\\\\GreFirstWord\{\\\\GreFirstSyllable\{\\\\GreElision\{\\\\GreFirstSyllableInitial\{l\}ision\}\}\}\}\{\}\}\{\{\}\{\\\\GreFirstWord\{\\\\GreFirstSyllable\{\\\\GreElision\{\\\\GreFirstSyllableInitial\{E\}lision\}\}\}\}\{\}\}\{\}\}\{\}\{\\\\GreFirstWord\}\{1\}\{\\\\GreSetNextSyllable\{\}\{\}\{\}\{\}\{\}\\\\GreLastOfLine\}\{\}\{\{18\}\{0\}\}\{\}\{%
\\\\GreSyllableNoteCount\{1\}%
\\\\GreLastOfScore\\\\GreGlyph\{\\\\GreCPPunctum\}\{9\}\{\\\\GreNextCustos\{9\}\{\}\}\{0\}%
\{%
\\\\GreGlyphHeights\{9\}\{9\}%
\}\{\}\{\}%
\}%
%
\\\\GreEndScore %
\\\\endinput %"
OUTCOME=$(eval $gregorio -d -S bad.gabc)

[[ "$OUTCOME" =~ $EXPECTED ]] || exit 1
