EXPECTEDERR="warning: can't write to file and stdout, writing on stdout
Usage: $gregorio [OPTION]... [-s | INPUT_FILE]
Try '$gregorio --help' for more information.
Proceeding anyway..."

OUTCOMEERR=$(eval $gregorio -S -o out.out test.gabc 2>&1 1> /dev/null)

[[ "$EXPECTEDERR" == "$OUTCOMEERR" ]] || exit 1

EXPECTEDOUT="% File generated by gregorio 6.0.0
\GregorioTeXAPIVersion{6.0.0}%
% Name: test
\GreBeginHeaders %
\GreHeader{name}{test}%
\GreEndHeaders %
\GreBeginScore{54f5ce67cd485db84bd200cd1a427f742093aa73}{9}{9}{0}{0}{}{4}{\GreInitialClefPosition{4}{0}}%
\GreSetLargestClef{c}{4}{3}{c}{0}{3}%
\GreScoreOpening{%
}{%
\GreSetInitialClef{c}{4}{3}{c}{0}{3}{1}%
}{%
}{\GreSyllable}{\GreSetFirstSyllableText{g}{}{}{{}{\GreFirstWord{}}{}}{{}{\GreFirstWord{\GreFirstSyllable{\GreFirstSyllableInitial{g}}}}{}}{}}{}{\GreFirstWord}{1}{\GreSetNextSyllable{}{}{}{}{}\GreLastOfLine}{}{{18}{0}}{}{%
\GreSyllableNoteCount{1}%
\GreLastOfScore\GreGlyph{\GreCPPunctum}{9}{\GreNextCustos{9}{}}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
%
\GreEndScore %
\endinput %"

OUTCOMEOUT=$(eval $gregorio -S -o out.out test.gabc)

[[ "$EXPECTEDOUT" == "$OUTCOMEOUT" ]] || exit 1
