name: brackets;
generated-by: gregorio 4.2.0-rc1-fix-844-394a23c-3859;
%%
(c3)Test(c/do1e) {e}fe([gv:\GreBracket{0}{7}{1}{}]efe[gv:\GreBracket{1}{7}{1}{}]) {f}gf([gv:\GreBracket{0}{8}{1}{}]fgf[gv:\GreBracket{1}{8}{1}{}]) {g}([gv:\GreBracket{0}{9}{0}{}]g[gv:\GreBracket{1}{9}{0}{}]) {a}m([gv:\GreBracket{0}{3}{12}{}]a/m[gv:\GreBracket{1}{3}{12}{}]) {e}/h([gv:\GreBracket{0}{7}{3}{}]e/h[gv:\GreBracket{1}{7}{3}{}]) {g}e([gv:\GreBracket{0}{7}{2}{}]ge[gv:\GreBracket{1}{7}{2}{}]) 
