name: flexus-stroke;
generated-by: gregorio 6.1.0-ctan-9d7ca2d9-4727;
%%
(c4)Flexus Stroke(g) (::z)
@<v>$[</v>ghghwj<v>$]</v>(g@hg@hwj) (::z)
@<v>$[</v>ghg<v>$[</v>shape$:stroke<v>$]</v>hwj<v>$]</v>(g@hg[shape:stroke]@hwj) (::z)
@<v>$[</v>ghg<v>$[</v>shape$:junk$,stroke<v>$]</v>hwj<v>$]</v>(g@hg[shape:junk,stroke]@hwj) (::z)
@<v>$[</v>ghg<v>$[</v>shape$:stroke$,junk<v>$]</v>hwj<v>$]</v>(g@hg[shape:stroke,junk]@hwj) (::z)
@<v>$[</v>ghg<v>$[</v>shape$:junk$,stroke$,junk<v>$]</v>hwj<v>$]</v>(g@hg[shape:junk,stroke,junk]@hwj) (::)

