name: flexus-stroke;
generated-by: gregorio 6.0.0-fix-1558-2991e642-4526;
%%
(c4)Flexus Stroke(g) (::z)
@<v>$[</v>ghghwj<v>$]</v>(g@hg@hwj) (::z)
@<v>$[</v>ghg<v>$[</v>shape$:stroke<v>$]</v>hwj<v>$]</v>(g@hg[shape:stroke]@hwj) (::z)
@<v>$[</v>ghg<v>$[</v>shape$:junk$,stroke<v>$]</v>hwj<v>$]</v>(g@hg[shape:junk,stroke]@hwj) (::z)
@<v>$[</v>ghg<v>$[</v>shape$:stroke$,junk<v>$]</v>hwj<v>$]</v>(g@hg[shape:stroke,junk]@hwj) (::z)
@<v>$[</v>ghg<v>$[</v>shape$:junk$,stroke$,junk<v>$]</v>hwj<v>$]</v>(g@hg[shape:junk,stroke,junk]@hwj) (::z)

