name: bottom hepisemus;
generated-by: gregorio 5.2.1--a6b7641f-4476;
%%
(c3)abc(g_0h_ g_h_ g_0_1h_g_0_1) (;)
j_k_l(j_k_l) j_0k_0l(j_0k_0l) j_0!k_0l(j_0!k_0lZ)
def(g_0_1 g_3 g_4 g_5 g_03 g_04 g_05 g_13 g_14 g_15 g_05_13 g_04_14 g_03_15Z)
ghi(g_g_g_ g_g_3g_ g_g_4g_ g_g_5g_ g_2g_3g_ g_2g_4g_ g_2g_5g_Z)
jkl(h_g_/ho0_f_ h_g_/go0_f_ h_g_2/ho0_f_ h_g_2/go0_f_Z)
abc(f_13hf_15) gná(g_h_g_) gná(g_h_g_//e!f'g) gvFE_5(gvF0E0_5) hvGF_5(hvG0F0_5Z)
ivH_4GF(ivH0_4G0F0) gf_15f_d_!ewf_(gf_15/f_d_!ewf_) gf_15E_D_ewf_ED(gf_15E0_D0_/ewf_E0D0) h_g_3!hwi(h_g_3!hwi) hih_15(hih_15Z)
f_eg(f_eg) f_egf(f_egf) ef_eg(ef_eg) ef_egf(ef_egf) f_e_g(f_e_g) f_e_gf(f_e_gf) ef_e_g(ef_e_g) ef_e_gf(ef_e_gfZ)
g_1hi(g_1hi) g_1/hi(g_1/hi) ixd!ewg_/hi(ixd!ewg_/hi) g_0g__(g_0_1g_) g_1g__(g_0_1g_) g_g__(g_0_1g_) $-g_ig'ig~(-g_ig'ig~) $-g_ig(-g_ig) (:)

