name: horizontal episema tuning;
generated-by: gregorio 4.1.0-beta3-fix-905-2e2e49a-3303;
%%
(c4)Horizontal Episema Tuning(gZ)
(g_0)(g_0[uh:l])(g_0[uh:m])(g_0[uh:h]) (g_0[uh:l])(g_0[uh:h])(g_0[uh:ol])(g_0[uh:oh]) (:)
(h_0)(h_0[uh:l])(h_0[uh:m])(h_0[uh:h]) (h_0[uh:l])(h_0[uh:h])(h_0[uh:ol])(h_0[uh:oh]) (:)
(g_1)(g_1[oh:l])(g_1[oh:m])(g_1[oh:h]) (g_1[oh:ul])(g_1[oh:uh])(g_1[oh:l])(g_1[oh:h]) (:)
(h_1)(h_1[oh:l])(h_1[oh:m])(h_1[oh:h]) (h_1[oh:ul])(h_1[oh:uh])(h_1[oh:l])(h_1[oh:h]) (:)
(g_0[oh:-0.5mm]) (g_0[uh:+0.5mm]) (::)
ma(dc)gis(f_h)ter(ixg_h_i_0>) ves(hv_G_F_E_/fwgfg)ter,(g.) (::)
ma(dc)gis([uh:m{]f_h)ter(ixg_h_i_0[uh}]>) ves(hv_G_F_E_/fwgfg)ter,(g.) (::)
ma(dc)gis([uh{]f_h)ter(ixg_h_i_0[uh}]>) ves(hv_G_F_E_/fwgfg)ter,(g.) (::)
ma(dc)gis(d_)ter(ixg_h_i_0>) ves(hv_G_F_E_/fwgfg)ter,(g.) (::)
ma(dc)gis(d_[oh:m])ter([uh:m{]ixg_h_i_0[uh}]>) ves(hv_G_F_E_/fwgfg)ter,(g.) (::)
ma(dc)gis([oh{]fh_1)ter(ixg_1h_1i_1[oh}]>) ves(hv_G_F_E_/fwgfg)ter,(g.) (::)

