name: nocustos;
generated-by: gregorio 4.2.0-develop-6c46cbd-4063;
%%
(c4)Nocustos1a(a) nocustos1b(b) nocustos1c(c) nocustos1d(d) nocustos1e(e) nocustos1f(f::[nocustos])
custos1a(aZ)
custos1b(b) custos1c(c) custos1d(d) custos1e(e) custos1f(f) custos1g(g) custos1h(h) custos1i(i) nocustos2a(a) nocustos2b(b) nocustos2c(c) nocustos2d(d) nocustos2e(e) nocustos2f(f::[nocustos])
really really really long text that will push the word to the end of the line c{u}stos2a(a) custos2b(b) custos2c(c) custos2d(d) custos2e(e) custos2f(f) custos2g(g) custos2h(h) custos2i(i) custos2j(j) custos2k(k) custos2l(l) custos2m(m) 
