name: punctum inclinatum 2;
generated-by: gregorio 4.1.1-fix-987-7e0bcb1-3583;
%%
(c4)jvI(jv/I) jvIH(jvIH) jvIHG(jvIHG) jvIHGF(jvIHGF) jvIHGFE(jvIHGFE) jvIHGFED(jv/IHGFED) (:)
Dev(Dev) DEfv(DEfv) DEFgv(DEFgv) DEFGhv(DEFGhv) DEFGHiv(DEFGHiv) DEFGHIjv(DEFGHI/jv) (:)
D!ev(D!ev) DE!fv(DE!fv) DEF!gv(DEF!gv) DEFG!hv(DEFG!hv) DEFGH!iv(DEFGH!iv) DEFGHI!jv(DEFGHI!jv) (:)
jvIHGFEDEFGHIjv(jv/IHGFEDEFGHI/jv) (:)
DED(DED) DEFE(DEFE) DEFGF(DEFGF) DEFGHG(DEFGHG) JIJ(JIJ) JIHI(JIHI) JIHGH(JIHGH) JIHGFG(JIHGFG) (::Z)
G.(G.) G<sp>~</sp>.(G.~) G.H.<sp>~</sp>(G.H.~) IrH<r(IrHr<<) DrE<r(DrEr<<) Gr<I<sp>~</sp>(Gr<I~) GG(GG) DJ(DJ) (::)

