name: punctum inclinatum 2;
generated-by: gregorio 4.1.0-beta1-fix-697-6ed5df5-3051;
%%
(c4)jvI(jvI) jvIH(jvIH) jvIHG(jvIHG) jvIHGF(jvIHGF) jvIHGFE(jvIHGFE) jvIHGFED(jvIHGFED) (:) Dev(Dev) DEfv(DEfv) DEFgv(DEFgv) DEFGhv(DEFGhv) DEFGHiv(DEFGHiv) DEFGHIjv(DEFGHIjv) (:) jvIHGFEDEFGHIjv(jvIHGFEDEFGHIjv) (:) DED(DED) DEFE(DEFE) DEFGF(DEFGF) DEFGHG(DEFGHG) JIJ(JIJ) JIHI(JIHI) JIHGH(JIHGH) JIHGFG(JIHGFG) (::Z) G.(G.) G<sp>~</sp>.(G.~) G.H.<sp>~</sp>(G.H.~) (::) 
