name: punctum inclinatum;
generated-by: gregorio 5.2.1-fix-1515-681ef1f2-4478;
%%
(c3)@<v>$[</v>HGhg<v>$]</v>(H0G0@hg) @<v>$[</v>IGhf<v>$]</v>(I0G0@hf) @<v>$[</v>JGhe<v>$]</v>(J0G0@he) @<v>$[</v>KGhd<v>$]</v>(K0G0@hd) @<v>$[</v>LGhc<v>$]</v>(L0G0@hcZ)
@<v>$[</v>FGhg<v>$]</v>(F1G1@hg) @<v>$[</v>EG_i_g<v>$]</v>(E1G1_@i_g) @<v>$[</v>DGjg<v>$]</v>(D1G1@jg) @<v>$[</v>CGkg<v>$]</v>(C1G1@kg) @<v>$[</v>BGlg<v>$]</v>(B1G1@lg) @<v>$[</v>EG_ig<v>$]</v>(E1G1_@igZ)
@<v>$[</v>HGfc<v>$]</v>(H0G0@fc) @<v>$[</v>IG_ec<v>$]</v>(I0G0_@ec) @<v>$[</v>JG_d_c<v>$]</v>(J0G0_@d_c) @<v>$[</v>HG_h_fg<v>$]</v>(H0G0_@h_fg) @<v>$[</v>IGifg<v>$]</v>(I0G0@ifg) @<v>$[</v>JGjfg<v>$]</v>(J0G0@jfgZ)
@<v>$[</v>HG<sp>~</sp>hg<v>$]</v>(H0G~@hg) @<v>$[</v>IG<sp>~</sp>hf<v>$]</v>(I0G~@hf) @<v>$[</v>JG<sp>~</sp>he<v>$]</v>(J0G~@he) @<v>$[</v>KG<sp>~</sp>hd<v>$]</v>(K0G~@hd) @<v>$[</v>LG<sp>~</sp>hc<v>$]</v>(L0G~@hcZ)
@<v>$[</v>FG<sp>~</sp>hg<v>$]</v>(F0G~@hg) @<v>$[</v>EG<sp>~</sp>ig<v>$]</v>(E0G~@ig) @<v>$[</v>DG<sp>~</sp>jg<v>$]</v>(D0G~@jg) @<v>$[</v>CG<sp>~</sp>kg<v>$]</v>(C0G~@kg) @<v>$[</v>BG<sp>~</sp>lg<v>$]</v>(B0G~@lgZ)
@<v>$[</v>H<sp>~</sp>G<sp>~</sp>hg<v>$]</v>(H~G~@hg) @<v>$[</v>I<sp>~</sp>G<sp>~</sp>hf<v>$]</v>(I~G~@hf) @<v>$[</v>J<sp>~</sp>G<sp>~</sp>he<v>$]</v>(J~G~@he) @<v>$[</v>K<sp>~</sp>G<sp>~</sp>hd<v>$]</v>(K~G~@hd) @<v>$[</v>L<sp>~</sp>G<sp>~</sp>hc<v>$]</v>(L~G~@hcZ)
@<v>$[</v>F<sp>~</sp>G<sp>~</sp>hg<v>$]</v>(F~G~@hg) @<v>$[</v>E<sp>~</sp>G<sp>~</sp>ig<v>$]</v>(E~G~@ig) @<v>$[</v>D<sp>~</sp>G<sp>~</sp>jg<v>$]</v>(D~G~@jg) @<v>$[</v>C<sp>~</sp>G<sp>~</sp>kg<v>$]</v>(C~G~@kg) @<v>$[</v>B<sp>~</sp>G<sp>~</sp>lg<v>$]</v>(B~G~@lgZ)
@<v>$[</v>HG$<hg<v>$]</v>(H0G<@hg) @<v>$[</v>IG$<hf<v>$]</v>(I0G<@hf) @<v>$[</v>JG$<he<v>$]</v>(J0G<@he) @<v>$[</v>KG$<hd<v>$]</v>(K0G<@hd) @<v>$[</v>LG$<hc<v>$]</v>(L0G<@hcZ)
@<v>$[</v>FG$<hg<v>$]</v>(F0G<@hg) @<v>$[</v>EG$<ig<v>$]</v>(E0G<@ig) @<v>$[</v>DG$<jg<v>$]</v>(D0G<@jg) @<v>$[</v>CG$<kg<v>$]</v>(C0G<@kg) @<v>$[</v>BG$<lg<v>$]</v>(B0G<@lg) (::)

