name: bivirga, bistropha, etc.;
generated-by: gregorio 4.1.0-beta3-fix-905-2e2e49a-3303;
%%
(c3)gvv(gvgv) gvgv(gvgv) gvvv(gvgvgv) gvgvgv(gvgvgv) gss(gsgs) gsgs(gsgs) gsss(gsgsgs) gsgsgs(gsgsgsZ)
gss<(gsgs<) gsgs<(gsgs<) gsss<(gsgsgs<) gsgsgs<(gsgsgs<) gsgs<s<(gsgs<) gs<gs<gs<(gs</gs</gs<Z)
hvhvv(hvhvhv) hvvhv(hvhvhv) hshss(hshshs) hsshs(hshshs) hhhhh<hhh>hhhh<sp>~</sp>hh(h/hhhh</hhh>/hhhh~/hhZ)
hvhvhvhvhv<hvhvhv>hvhvhvhv<sp>~</sp>hvhv(hvhvhv/hvhv</hvhvhv>/hvhvhvhv~/hvhvZ)
hVhVhVhVhV<hVhVhV>hVhVhVhV<sp>~</sp>hVhV(hV/hVhVhVhV</hVhVhV>/hVhVhVhV~/hVhVZ)
hshshshshs<hshshs>hshshshs<sp>~</sp>hshs(hshshs/hshs</hshshs</hshshshs~/hshs) (::)

