name: salicus;
generated-by: gregorio 6.1.0-ctan-9d7ca2d9-4727;
%%
(c3)fgoh(f/go1h) f!goh(f!go1h) fgOh(fgO1h) egoh(e/go1h) egOh(egO1h) egoi(e/go1i) egOi(egO1iZ)
fgoh$<(f/go1h<) egoh$<(e/go1h<) egoi$<(e/go1i<) fgoh>(f/go1h>) egoh>(e/go1h>) egoi>(e/go1i>) fgoh<sp>~</sp>(f/go1h~) egoh<sp>~</sp>(e/go1h~) egoi<sp>~</sp>(e/go1i~Z)
fgOh$<(fgO1h<) egOh$<(egO1h<) egOi$<(egO1i<) fgOh>(fgO1h>) egOh>(egO1h>) egOi>(egO1i>) fgOh<sp>~</sp>(fgO1h~) egOh<sp>~</sp>(egO1h~) egOi<sp>~</sp>(egO1i~Z)
fgOh'_(fgO1h'_) egOh'_(egO1h'_) egOi'_(egO1i'_) fgOh$<'_(fgO1h'_<) egOh$<'_(egO1h'_<) egOi$<'_(egO1i'_<) f'_gOh>(f'_gO1h>) egO'_h>(egO1'_h>) egO'_i>(egO1'_i>) fgOh<sp>~</sp>'_(fgO1h'_~) egOh<sp>~</sp>'_(egO1h'_~) egOi<sp>~</sp>'_(egO1i'_~) 
