name: salicus;
generated-by: gregorio 4.1.0-beta1-fix-697-6e47e86-3160;
%%
(c3)fgoh(f/goh) f!goh(f!goh) fgOh(fgOh) egoh(e/goh) egOh(egOh) egoi(e/goi) egOi(egOiZ) fgoh<(f/goh<) egoh<(e/goh<) egoi<(e/goi<) fgoh>(f/goh>) egoh>(e/goh>) egoi>(e/goi>) fgoh<sp>~</sp>(f/goh~) egoh<sp>~</sp>(e/goh~) egoi<sp>~</sp>(e/goi~Z) fgOh<(fgOh<) egOh<(egOh<) egOi<(egOi<) fgOh>(fgOh>) egOh>(egOh>) egOi>(egOi>) fgOh<sp>~</sp>(fgOh~) egOh<sp>~</sp>(egOh~) egOi<sp>~</sp>(egOi~Z) fgOh'_(fgOh'_) egOh'_(egOh'_) egOi'_(egOi'_) fgOh<'_(fgOh'_<) egOh<'_(egOh'_<) egOi<'_(egOi'_<) f'_gOh>(f'_gOh>) egO'_h>(egO'_h>) egO'_i>(egO'_i>) fgOh<sp>~</sp>'_(fgOh'_~) egOh<sp>~</sp>'_(egOh'_~) egOi<sp>~</sp>'_(egOi'_~Z) 
