name: salicus flexus;
generated-by: gregorio 4.1.0-beta3-fix-905-2e2e49a-3303;
%%
(c3)fgOhg(fgO1hg) egOhf(egO1hf) fgOhg<(fgO1hg<) egOhf<(egO1hf<) fgOhg>(fgO1hg>) egOhf>(egO1hf>) fgOhg<sp>~</sp>(fgO1hg~) egOhf<sp>~</sp>(egO1hf~Z)
f'_gOhg(f'_gO1hg) egO'_hf(egO1'_hf) fgOh'_g<(fgO1h'_g<) egOhf<'_(egO1hf'_<) fgOhg>'_(fgO1hg'_>) egO'_hf>(egO1'_hf>) fgOhg<sp>~</sp>'_(fgO1hg'_~) egOhf<sp>~</sp>'_(egO1hf'_~Z)

