name: shapes;
generated-by: gregorio 4.2.0-beta1-fix-856-7ee4d55-3666;
%%
(c3)fg(fg) gvFE(gvF0E0) ghg(ghg) ghgh(ghgh) ghghg(ghghg) gqh(gqh) gFE<(gF0E<) gFE<sp>~</sp>(gF0E~) gs(gs) gs<(gs<) gf(gf) g=(g=) h=(h=) fvE'D.(fvE0'D0.) gvFD(gvF0D0) hvGD(hvG0D0) ivHD(ivH0D0) iv>(iv>) ige(ig/e) ige<sp>~</sp>(ige~) dfec<sp>~</sp>(dfec~) dwfec<sp>~</sp>(dwfec~) egi(egi) egi<sp>~</sp>(egi~) GrGrFr(GrGrFr) GrGrFr<(GrGrFr<<) FrGrFr_0(FrGrFr_0) GrFrEr(GrFrEr) Gr<(Gr<<Z)
-fg(-fg) -f'g(-f'g) -f'1g(-f'1g) gf<sp>~</sp>(gf~) g'f<sp>~</sp>(g'f~) g'0f<sp>~</sp>(g'0f~) (:)
gor(go1r) go0r(go0r) gor<sp>~</sp>(gor~) {g}r/Gr/go0r(gr/Gr/go0rZ)
-fg>(-fg>) -fg<(-fg<) fwg>(fwg>) ivH<(iv/H<) fWg(fWg) hs<(hs<) g'h'..(g'h'..) g'h..'(g'h'..) gv(gv) hv(hv) gV(gV) hV(hV) gO(gO1) hO(hO0) gfd<sp>~</sp>(gfd~) hge<sp>~</sp>(hge~) g.fd<sp>~</sp>(g.fd~) bab(bab) baba(baba) abab(abab) ababa(ababa) lmlm(lmlm) lmlml(lmlml) ijiml(ijiml) gohghg(go1hghg) gwigig(gwigig) ghi<(ghi<) ghi>(ghi>) ghi<sp>~</sp>(ghi~) G<H<(G<H<) Gr<sp>~</sp>(Gr) gor<sp>~</sp>(gor~) fohd(fo1@hd) fohd<sp>~</sp>(fo1@hd~) h+(h+) 
