name: torculus resupinus;
generated-by: gregorio 5.2.1--a6b7641f-4476;
%%
(c3){gwhgi}(gwhgi) fwifg<sp>~</sp>(fwifg~) fwifg(fwifgZ)
{gwhg$.i}(gwhg.i) fwif$.g(fwif.g) {gwhgi$.}(gwhgi.) fwifg.(fwifg.) {gw$.h$.g$.i}(gw.h.g.i) fw$.i$.f$.g(fw.i.f.g) {gwh}gi$..(gwhgi..) fwifg$..(fwifg..Z)
{gw_}hgi(gw_hgi) fw_ifg(fw_ifg) {gwh}_gi(gwh_gi) fwi_fg(fwi_fg) {gwh}g_i(gwhg_i) fwif_g(fwif_g) {gwh}gi_(gwhgi_) fwifg_(fwifg_) {gwh}g_i_(gwhg_i_) fwif_g_(fwif_g_) {gwh}_g_i(gwh_g_i) fwi_f_g(fwi_f_g) {gw_h}_gi(gw_h_gi) fw_i_fg(fw_i_fg) {gw_h}_g_i(gw_h_g_i) fw_i_f_g(fw_i_f_g) {gw_h}_g_i_(gw_h_g_i_) fw_i_f_g_(fw_i_f_g_Z)
{gw'}hgi(gw'hgi) fw'ifg(fw'ifg) {gw}h'gi(gwh'gi) fwi'fg(fwi'fg) {gw}hg'i(gwhg'i) fwif'g(fwif'g) {gw}hgi'(gwhgi') fwifg'(fwifg') {gw}'h'g'i(gw'h'g'i) fw'i'f'g(fw'i'f'g) {gw}'h'g'i'(gw'h'g'i') fw'i'f'g'(fw'i'f'g'Z)
fwif$.'g(fwif'.g) {gw}'h'g$.'i(gw'h'g'.i) fw'i'f$.'g(fw'i'f'.g) {gw}'h'g$.'i$.'(gw'h'g'.i'.)fw'i'f$.'g$.'(fw'.i'.f'.g'.Z)

