name: 5-lines;
staff-lines: 5;
generated-by: gregorio 4.1.0-beta3-fix-905-ae989ff-3288;
%%
(c5)a_0'(a'_0) a_0(a_0) b_0(b_0) (`)
b/c_0(b/c_0) c_0(c_0) d_0(d_0) (,)
efg/0hi/0jk(efg/0hi/0jk) (;)
l_(l_) m_(m_) m_/n(m_/n) (:)
N_(N_) P_(P_) P_'1(P'1_) (::Z)
a+(a+) b+(b+) c+(c+) d+(d+) e+(e+) f+(f+) g+(g+) h+(h+) i+(i+) j+(j+) k+(k+) l+(l+) m+(m+) n+(n+) p+(p+Z)
g(g) ,1(;1)
,2(;2)
,3(;3)
,4(;4)
,5(;5)
,6(;6)
,7(;7)
,8(;8)
;1(;1)
;2(;2)
;3(;3)
;4(;4)
;5(;5)
;6(;6)
;7(;7)
;8(;8Z)
g(g) (z0::f2)
e(e) fr1(fr1) fr2(fr2) mr3(mr3) nr4(nr4) pr5(pr5) (::)

