name: Factus est cum Alleluia;
office-part: Communio;
mode: 7;
book: Graduale Romanum, 1961, p. 296;
transcriber: Andrew Hinkley, Jakub Jelínek;
nabc-lines: 1;
generated-by: gregorio 4.1.0-beta1-fix-697-6e47e86-3160;
%%
(c3)FAc(e)tus(ei) est(i) re(i)pén(i)te(e.) de(i) cæ(i)lo(h) so(kjki)nus(i.) (,) ad(i)ve(i)ni(ij)én(ji~)tis(j_i) spí(hj)ri(i)tus(h) ve(h.)he(f!gwh)mén(hi~)tis,(h.) (;) u(hg)bi(h) e(iji)rant(hih) se(hg)dén(fhG'E)tes,(fe..) (,) al(eg~)le(gv./fhg)lú(e_f_e_)ia:(e.) (:) et(e) re(f)plé(h!i'j)ti(i) sunt(i) om(ij~)nes(i) Spí(j)ri(i)tu(h) Sanc(ij~)to,(j.) (;) lo(i)quén(hg/h_ih~)tes(f) ma(eg~)gná(g_h_g_//e!f'g)li(fd)a(f) De(e_f_e_)i,(e.) (;) al(eg~)le(g)lú(hih)ia,(f.) (,) al(eg~)le(gv./fhg)lú(e_f_e_)ia.(e.) (::) 
