name: Litaniae;
generated-by: gregorio 6.2.0-multiline-lyrics-374-14319c6e-5079;
%%
(c4)<sp>V/</sp>$. Sanc|Sanc|Sanc||Ma|Ma|Ma|Ma|Ma|Ma|Ma(h)|ta|ta||ter|||ter|ter||ter(h) |||| di||| in| in||(h) |||Ma|||||||([gv:\GreBracket${0$}${9$}${10$}${$}]hg[gv:\GreBracket${1$}${9$}${10$}${$}])ta|De|Vir||vi|ter|ter|vi|te|ter|ad(g) Ma|i|go|ter|næ| pu| cas|o|me| a|mi(h)rí| Gé| Vír| Chri| Grá|rís|tís|lá|rá|má|rá(ixir1)|ni|gi||ti|si|si|||bi|bi(gr)a$,|trix$,|num$,|sti$,|æ$,|ma$,|ma$,|ta$,|ta$,|lis$,|lis,(g.) (:)
<sp>R/</sp>$. o(g)ra(f) pro(g) no(h)bis.(h) (::)

