name: Pópulus Sion;
office-part: Introitus;
occasion: Dominica II Adventus;
date: 2006;
transcriber: Elie Roux;
transcription-date: 2006;
style: modern;
generated-by: gregorio 4.2.0-beta1-fix-856-7ee4d55-3666;
%%
(c3)Pó(eh)pu(g)lus(h) Si(hi)on,(hgh.) *(;)
ec(hihi)ce(e.) Dó(e.f!gwh/hi)mi(h){n}us(h) vé(hi)ni(ig//ih)et(h.) (,)
ad(iv./hig) sal(fe)ván(ghg)das(fg) gen(e_f_e_)tes(e.) :(:)
et(e) au(eh)dí(hhi)tam(i) fá(kjki)ci(i)et(i) Dó(ij)mi(ihi)nus(iv./hiH0F0) (,)
gló(h!i'j)ri(ji!kvJ0I0)am(ij) vo(j.i!jwk)cis(ji) su(i_j_i_)æ,(i.) (;)
in(e) læ(e)tí(e!f'h)ti(h)a(hi!jVji) cor(gh!ijI0'H<)dis(ih/hf!gwh) ve(e_f_e_)stri.(e) Ps.(::)
Qui(ehg) re(hi)gis(i) I(i)sra(i)el,(hj) in(j)tén(ji)de(ij..) :*(:)
qui(ig) de(hi)dú(i)cis(i) vel(i)ut(i!jwk) o(i')vem(h) Jo(hhh)seph.(fe..) (::)
Gló(ehg)ri(hi)a(i) Pa(i)tri.(i) (:)
E(i) u(i!jwk) o(i) u(h) a(hhh) e(fe..) (::)

