name: probare omnia capita;
gabc-copyright: Matt 10:8b;
score-copyright: nescio;
office-part: introitus?;
occasion: numquam;
meter: nihil;
commentary: invocatio;
arranger: quis?;
author: Innominatus;
date: xxi c;
manuscript: ms;
manuscript-reference: quid?;
manuscript-storage-place: utopia;
book: Liber scriptus;
transcriber: petrus (non sanctus);
transcription-date: 2009;
mode: 6;
mode-modifier: t.;
user-notes: this file just shows all the possible header fields;
user-notes: of course, it doesn't make sense to use all at once;
annotation: IN.;
annotation: III.;
language: Latin;
x-extheader1: external header 1;
x-ext-header-2: external header 2;
x-extheader1: external header 3;
generated-by: gregorio 4.0.1-fix-756-7fb5812-2890;
%%
(c4)IN(ed~) nó(g)mi(hj)ne(j) Je(ij)su(j.) 
