name: probare omnia capita;
gabc-copyright: Matt 10:8b;
score-copyright: nescio;
office-part: introitus?;
occasion: numquam;
meter: nihil;
commentary: invocatio;
arranger: quis?;
language: Latin;
generated-by: gregorio 4.0.0-rc2-fix-670-fefd9da-2697;
author: Innominatus;
date: xxi c;
manuscript: ms;
manuscript-reference: quid?;
manuscript-storage-place: utopia;
book: Liber scriptus;
transcriber: petrus (non sanctus);
transcription-date: 2009;
mode: 6;
annotation: IN.;
annotation: III.;
initial-style: 2;
user-notes: of course, it doesn't make sense to use all at once;
%%
(c4)IN(ed~) nó(g)mi(hj)ne(j) Je(ij)su(j.) 
