name: probare omnia capita;
gabc-copyright: Matt 10:8b;
score-copyright: nescio;
office-part: introitus?;
occasion: numquam;
meter: nihil;
commentary: invocatio;
arranger: quis?;
language: Latin;
generated-by: gregorio 4.0.1-fix-756-8af1368-2867;
author: Innominatus;
date: xxi c;
manuscript: ms;
manuscript-reference: quid?;
manuscript-storage-place: utopia;
book: Liber scriptus;
transcriber: petrus (non sanctus);
transcription-date: 2009;
mode: 6;
mode-modifier: t.;
annotation: IN.;
annotation: III.;
user-notes: of course, it doesn't make sense to use all at once;
x-extheader1: external header 1;
x-ext-header-2: external header 2;
x-extheader1: external header 3;
%%
(c4)IN(ed~) nó(g)mi(hj)ne(j) Je(ij)su(j.) 
