name: fix-20;
generated-by: gregorio 4.1.0-beta3-fix-905-2e2e49a-3303;
%%
(c3)scandicus(ghi) scandicus-desc(ghi>) scandicus-asc(ghi<) scandicus-demi(ghi~) (::z)
pesq-punctum(gqh/i) pesq-punctum-desc(gqh/i>) pesq-punctum-asc(gqh/i<) pesq-punctum-demi(gqh/i~) (::z)
qpes-punctum(gwh/i) qpes-punctum-desc(gwh/i>) qpes-punctum-asc(gwh/i<) qpes-punctum-demi(gwh/i~) (::z)
qpesq-punctum(gWh/i) qpesq-punctum-desc(gWh/i>) qpesq-punctum-asc(gWh/i<) qpesq-punctum-demi(gWh/i~) (::z)
quassus-punctum(go1h/i) quassus-punctum-desc(go1h/i>) quassus-punctum-asc(go1h/i<) quassus-punctum-demi(go1h/i~) (::z)
pes-debi-punctum(-gh/i) pes-debi-punctum-desc(-gh/i>) pes-debi-punctum-asc(-gh/i<) pes-debi-punctum-demi(-gh/i~) (::z)

