name: fix-20;
generated-by: gregorio 4.1.0-beta1-fix-697-b746933-3049;
%%
(c3)scandicus(ghi) scandicus-desc(ghi>) scandicus-asc(ghi<) scandicus-demi(ghi~) (::z) pesq-punctum(gqhi) pesq-punctum-desc(gqhi>) pesq-punctum-asc(gqhi<) pesq-punctum-demi(gqhi~) (::z) qpes-punctum(gwhi) qpes-punctum-desc(gwhi>) qpes-punctum-asc(gwhi<) qpes-punctum-demi(gwhi~) (::z) qpesq-punctum(gWhi) qpesq-punctum-desc(gWhi>) qpesq-punctum-asc(gWhi<) qpesq-punctum-demi(gWhi~) (::z) quassus-punctum(gohi) quassus-punctum-desc(gohi>) quassus-punctum-asc(gohi<) quassus-punctum-demi(gohi~) (::z) pes-debi-punctum(-ghi) pes-debi-punctum-desc(-ghi>) pes-debi-punctum-asc(-ghi<) pes-debi-punctum-demi(-ghi~) (::z) 
